### ISSUE TITLE
Composing Window

### ISSUE THREAD

**Issue by Oronhyatekha** [drakkar1969/MailSpring-Arc-Theme#1]
Hey,
unfortunately since the last update, the send button in the composing window is just white instead of blue.
Is it possible to fix this. I like this theme a lot.
![composing window arc theme issue](https://user-images.githubusercontent.com/14246140/50822575-5660fc80-1332-11e9-911a-171ac5d7f325.PNG)

**Comment by drakkar1969** [comment]
Also just noticed this, will look at a fix in the next few days - should be just a case of changed CSS selectors with recent Mailspring updates

Glad you like the theme :)

**Comment by drakkar1969** [comment]
Fixed in latest commit, let me know if any issues
