### ISSUE TITLE
custom  window frame icons

### ISSUE THREAD

**Issue by Oronhyatekha** [drakkar1969/MailSpring-Arc-Theme#2]
Is it possible to have the custom window frame icons from your theme on Mailspring for the windows platform? Windows 10 usees the default close, minimize and resize buttons.
![Unbenannt](https://user-images.githubusercontent.com/14246140/63453825-cb102380-c449-11e9-83b2-06e245a449fb.PNG)

**Comment by drakkar1969** [comment]
So sorry for the hugely delayed response.
I tried Mailspring on Windows and, as far as I can see, there is no option in preferences to use a custom window/window controls - as there is in the Linux version.
Which means the window buttons cannot be styled on Windows, as far as I know
